class Bar:
    def __init__(self, time, open, high, low, close, volume, bought_volume=0): ...

class Quote:
    def __init__(self, time, bid, ask, bid_size, ask_size): ...

class Trade:
    def __init__(self, time, price, size, taker=-1, trade_id=0): ...

class TimeSeries:
    def __init__(self, name, timeframe, max_series_length, process_every_update=True) -> None: ...

class OHLCV(TimeSeries):
    def __init__(self, name, timeframe, max_series_length) -> None: ...
